### ISSUE TITLE
🐛 SameFileError

### ISSUE THREAD

**Issue by neurosurd** [FCP-INDI/C-PAC#1449]
**Describe the bug**
Im persistently getting a SameFileError 
shutil.SameFileError: '/home/dseeburger3/MRT/CPACpreproc/work/resting_preproc_s1_ses-1/gen_motion_stats_afni_mean_3dvolreg_0/_scan_rest_1/calculate_FD/FD.1D' and '/home/dseeburger3/MRT/CPACpreproc/derivatives/output/pipeline_dolly_freq-filter_nuisance/s1_ses-1/frame_wise_displacement_power/_scan_rest_1/FD.1D' are the same file
 
Ive attached the log file and contents of the crash file
[pypeline.log](https://github.com/FCP-INDI/C-PAC/files/6039213/pypeline.log)
[SameFileError.txt](https://github.com/FCP-INDI/C-PAC/files/6039207/SameFileError.txt)
Similar to https://github.com/FCP-INDI/C-PAC/issues/1260

**Versions** 
 - cpac wrapper version: 0.3.1

 - Container Platform :
    - Singularity: 2.6.0-dist

**Additional context**
NiPype version used in the cpac wrapper is 1.1.2

**Comment by sgiavasis** [comment]
Hello @neurosurd,

This is a known issue in version 1.7.2 and prior. This is a crash file that gets generated because of an error where an output file is being written twice. Rest assured this does not impact the performance or results of your pipeline, and the range of outputs in your output directory should be complete.

Fortunately this error has been resolved in version 1.8.0, which will be available in the first week of March.

Please let me know if you have any further questions.

Best,
Steve
