### ISSUE TITLE
Pipeline Configuration Saving

### ISSUE THREAD

**Issue by ebridge2** [FCP-INDI/C-PAC#377]
Hi, while configuring the pipeline to test the benchmark dataset, I encounntered an issue. Note that I loaded the file, 'pipeline_config.yml' instead of 'benchmark_config.yml', as the benchmark package did not have either of these included and the Github master zip 'CPAC_master.zip' only included a working version of the pipeline_config.yml file (other file is empty, or I am having trouble opening it). I am using CentOS6.5 distribution and use the Anaconda distribution of Python (Python 2.7.6). I have the operating system installed to a Virtual Box. 

Now to the issue. When I go to save the pipeline, I receive the following notification from the terminal:
 File "/home/Eric/anaconda/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 707, in submit_item
    dlg.SetFilterIndex(2)
  File "/home/Eric/anaconda/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_windows.py", line 3185, in SetFilterIndex
    return _windows_.FileDialog_SetFilterIndex(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ./src/gtk/filectrl.cpp(203) in SetFilterIndex(): wxGtkFileChooser::SetFilterIndex - bad filter index

and cannot figure out why. I believe this error to be fairly similar to #360, https://github.com/FCP-INDI/C-PAC/issues/360, which has an error at line 697 instead of 707. The issue occurs when I try to save the pipeline after editing to add my user-specific paths. I have tried commenting out the offending line (line 707), but this does not resolve the situation and have un-commented it out. I believe this error to be fairly similar to #360, https://github.com/FCP-INDI/C-PAC/issues/360. Thanks!

@jovo

**Comment by dclark87** [comment]
Hey @ebridge2 

I believe we can close the orginal issue posted here in regards to the wxPython error you were getting (it has since been implemented in our 0.3.9_development branch).

However, in regards to the  'Error Creating CPAC subject list.('Anatomical Data template incorrect. No such file or directory %s' you were getting. I believe you want to change your template from:

/home/Eric/datasets/pac_datasets/cpac_benchmark/%s/%s/session_1/site_1/mprage.nii.gz

to:

/home/Eric/datasets/pac_datasets/cpac_benchmark/%s/%s/session_1/anat_1/mprage.nii.gz

and functional to:

/home/Eric/datasets/pac_datasets/cpac_benchmark/%s/%s/session_1/rest_1/rest.nii.gz

As the site should be the first %s (which is site_1 folder in the benchmark) and the subject should be the second %s.
