### ISSUE TITLE
Error at check timeseries

### ISSUE THREAD

**Issue by orcasha** [FCP-INDI/C-PAC#417]
Hi, 

I'm having problems running a dual regression analysis. CPAC runs the spatial regression and extracts the ROI time series fine but outputs an error at check_timeseries. I've tracked the problem to the following messages: 

def check_ts(in_file):\\n    import numpy as np\\n    timepoints, rois = np.loadtxt(in_file).shape\\n    if rois > timepoints:\\n        message = (\'\\\\n\\\\n\\\\n****The number of timepoints (\' + str(timepoints)\\n                   + \') is smaller than the number of ROIs to run (\'\\n                   + str(rois) + \') - therefore the GLM is\'\\n                   + \' underspecified and can\\\\\'t run.****\\\\n\\\\n\\\\n\')\\n        print(message)\\n        raise Exception(message)\\n    else:\\n        return in_file\\n"\n.

and 

'need more than 1 value to unpack\nInterface Function failed to run. '

When I've checked individual timeseries however they have the same n as the volumes collected (140), so I'm really unsure what's going on.

**Comment by orcasha** [comment]
Hi Steven, 

I've got 13 ROIs and each patient has 140 volumes originally (less through scrubbing). 
Ps, sorry for the delayed response and happy new year!

**Comment by jpellman** [comment]
Hi orcasha,

The error message that you've been receiving should only appear if the number of ROIs you have exceeds the number of time points.  Since this is clearly not the case (13 is not greater than 140) something is afoot.  Can you find the text file that stores the timeseries for your analysis?  It should have 140 lines (one line for each timepoint) and 13 whitespace-separated columns for each ROI.  If this is the case, I would also check the end of each line to see if there is any text after the 13 ROI columns that could be affecting the program's ability to properly determine the correct number of ROIs.

Best,
John Pellman

**Comment by orcasha** [comment]
Hi John,

In the roi_timeseries output each ROI's time series (ts) is stored in a separate folder. The txt files have 141 lines (first line is #1 then the ts data after). I can't find a single txt file that has all ROI and ts data combined.

**Comment by jpellman** [comment]
Hi orcasha,

This is rather odd.  How is the ROI specification set up?  Are all of the ROIs defined within the same NifTI file, or does each ROI have its own NifTI?

**Comment by jpellman** [comment]
If all of the ROIs are in separate NifTI files, and all of the time series produced are single-column, you have actually uncovered a bug!  In trying to replicate what might be going on, I found that for single-column time series files, the method that we are using to determine the number of ROIs and number of timepoints will not work.  Basically, the "shape" method for Numpy arrays will return a tuple of length 1 for column vectors, since the second dimension is implied.  Therefore, (at line 86) only 'timepoints' can possibly be assigned a value, since only one value is returned in the tuple.  In fact, neither 'timepoints' nor 'rois' is being assigned any value, however, since a ValueError is thrown.

**Comment by sgiavasis** [comment]
Hi orcasha,

What are the names of those separate folders in the roi_timeseries directory?
