### ISSUE TITLE
"ImportError: No module named wx"

### ISSUE THREAD

**Issue by pixeluz** [FCP-INDI/C-PAC#430]
Hi. I'm trying to run C-PAC and I've encountered a problem. I've installed all the required dependencies and followed everything to install C-PAC on my Mac OS X (10.10.1 Yosemite). When I try to import CPAC in python, I get this message:

"Python 2.7.8 |Anaconda 2.1.0 (x86_64)| (default, Aug 21 2014, 15:21:46) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import CPAC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pixeluz/anaconda/lib/python2.7/site-packages/CPAC/__init__.py", line 18, in <module>
    import anat_preproc, \
  File "/Users/pixeluz/anaconda/lib/python2.7/site-packages/CPAC/GUI/__init__.py", line 1, in <module>
    from mainUI import run
  File "/Users/pixeluz/anaconda/lib/python2.7/site-packages/CPAC/GUI/mainUI.py", line 3, in <module>
    import wx
ImportError: No module named wx"

I know that it means it can't find the wxPython, but I've installed the wxPython3.0-osx-Cocoa-py2.7. using the installer available from wxPython's webpage. I tried uninstalling the package and re-installing it again, but to no avail. 

Does anyone know what I can do?

**Comment by jaipel** [comment]
Hi- it's possible that the wxPython installer is only installing the wx module in the original default Python installation provided by Apple, rather than Anaconda.  I would first search for where it is installed by trying the following Unix command in Terminal:  

find / -name "wx" | grep "site-packages/"

**Comment by pixeluz** [comment]
Thanks. You were right. Wx installer did not install the module into the proper Anaconda directory. So I managed to copy the package into Anaconda, and now "Import CPAC" works fine, but I've encountered another problem, and I saw that some people had a similar one, but there were no answers to this on the forum:

>>> CPAC.GUI.run()
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.

The same thing happens when I simply type cpac_gui into Terminal window. Is there a solution to that?

**Comment by jaipel** [comment]
Hello again- this seems to be a recurring problem with using wxPython on Macs.  This tutorial has more information: http://wiki.wxpython.org/wxPythonVirtualenvOnMac

The tutorial suggests placing the following shell script within Anaconda's bin directory:

#!/bin/bash

# what real Python executable to use
PYVER=2.7
PYTHON=/Library/Frameworks/Python.framework/Versions/$PYVER/bin/python$PYVER

# find the root of the virtualenv, it should be the parent of the dir this script is in
ENV=`$PYTHON -c "import os; print os.path.abspath(os.path.join(os.path.dirname(\"$0\"), '..'))"`

# now run Python with the virtualenv set as Python's HOME
export PYTHONHOME=$ENV 
exec $PYTHON "$@"

You should be able to copy and paste this into any ASCII text editor (TextEdit will not work, since it saves rtf files by default).  When that's done, you would only need to navigate to the Anaconda directory within Terminal, type "chmod +x <script_name>" and "./<script_name>"  where <script_name> is an arbitrary name ending with the ".sh" extension.

**Comment by pixeluz** [comment]
Thank you very much! I did what you suggested and now it runs without any problems. Thanks again.

**Comment by jaipel** [comment]
Excellent!  Happy preprocessing/analyzing. :)

**Comment by danlurie** [comment]
Just to add a bit of advice here, installing wx manually can be a huge pain (and not just on OS X).

Enthought Canopy includes a precompiled version of wx that works out of the box. I've found this to be the easiest way to get CPAC up and running.
