### ISSUE TITLE
cpac_run.py is recommending an invalid usage

### ISSUE THREAD

**Issue by alexsavio** [FCP-INDI/C-PAC#439]
cpac_run.py recommends this:
Usage: cpac_run.py /path/to/pipeline_config.yml /path/to/CPAC_subject_list.yml

But if you do that you will get this:
Traceback (most recent call last):
  File "/home/asavio/.envs/pydue/bin/cpac_run.py", line 45, in <module>
    check_custom_path(sys.argv[3])
IndexError: list index out of range

Clearly line 45 is to blame: https://github.com/FCP-INDI/C-PAC/blob/master/scripts/cpac_run.py#L45

**Comment by jpellman** [comment]
This should be able to be fixed with a quick sanity check to make sure that sys.argv is of length 4 before executing line 45 or length 5 before executing line 46.

**Comment by alexsavio** [comment]
I would be nice to process the Exceptions that are being raised from the cpac_runner.run call here.
I can make a PR for this issue, would that help?

**Comment by jpellman** [comment]
This can be more of a matter of style than anything else, but the code should be able to work perfectly well with just a fix to the sanity check in line 17.  Exception handling (from my understanding) usually isn't used unless you believe that something unanticipated might arise (like a function being passed a string instead of an int in strongly-typed languages; this might happen when trying to interface with third party software, like a MySQL or Oracle database).  With this function, there are only two acceptable uses- the user can enter in 2 arguments or 4 arguments.  Since we're planning on doing a code freeze soon, I'll inform the developers and let them decide how to proceed.
