### ISSUE TITLE
Motion plot question

### ISSUE THREAD

**Issue by Angel-Fernandez** [FCP-INDI/C-PAC#452]
Hi @jpellman ,

I've a couple of questions about motion plots (rotation and translation). The motion is calculated with respect to the first volume? and why the first volume has motion? Each line should start at zero, isn't it?

![trans plot](https://cloud.githubusercontent.com/assets/10339281/6751068/8890f478-cf00-11e4-95a1-f5cb19dacaef.jpg)

**Comment by jpellman** [comment]
Hi Angel,

C-PAC uses AFNI's 3dVolreg (with two passes) to calculate movement parameters for the functional scans.  This means that each volume is transformed by a function that aims to minimize the difference between each volume and the base volume (which is the first volume in this case).  Each transformation has a certain amount of error associated with it, since the AFNI algorithm is essentially making its best guess to align volumes to the first volume.  Since each volume has a transformation applied to it, even the first volume / base volume will be different.  Therefore, the discrepancy you note between the values you would expect the first volume to take (i.e., 0,0,0) and the values it does take (~0.1,~-0.275, ~-0.265) are likely error introduced by the fitting function.

Here are some slides (starting on slide 5) describing how 3dVolreg performs motion correction in more detail:
http://afni.nimh.nih.gov/pub/dist/edu/latest/afni_handouts/afni10_volreg_talairach.pdf

If you have more questions about motion correction, you should direct them towards the AFNI developers here:
http://afni.nimh.nih.gov/afni/community/board/

Best,
John Pellman

**Comment by jpellman** [comment]
Hi Angel,

I apologize for any confusion, but upon looking at C-PAC's code and internal documentation further it appears that C-PAC is actually not registering to the first volume (the default for 3dVolreg) as I had believed but rather to a mean functional image of all the voxel values at each timepoint.  This would explain the discrepancy you are finding in your plots.

**Comment by Angel-Fernandez** [comment]
Ok thanks.

**Comment by ccraddock** [comment]
Hello Angel,

I wanted to provide a little more of a clarification. C-PAC uses a two-stage procedure for motion correction. In the first stage 3dvolreg is used to realign the volumes to the mean image. The mean of the realigned images are then calculated and used as the base image in the second stage for a second realignment procedure. Since the base image is the mean and not any of the volumes, you may not get a volume that has zero displacement from the base as you would expect if it were one of the volumes. 

This procedure is outlined in more detail in the developer documentation here: 
http://fcp-indi.github.io/docs/developer/workflows/func_preproc.html.

Regards,
Cameron
