### ISSUE TITLE
remove cpac_centrality.py from scripts directory

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#464]
can move this to another directory that is not installed in setup.py

**Comment by souravsingh** [comment]
I would like to work on this.How Do I start?

**Comment by jpellman** [comment]
Hi Sourav,

I'm happy to hear that you would like to contribute to C-PAC.  My main
suggestion for starting out would be for you to download C-PAC, look for
bugs, and submit them to our issue tracker.  Since C-PAC is still alpha
software, there are many glitches out there, and being aware of those is
extremely helpful as we strive to improve the quality of the software.

Another thing that you can do to get started is familiarize yourself with
the software dependencies that C-PAC uses (i.e., AFNI, FSL, ANTs and
nipype).  For AFNI and FSL, there are a couple of tutorials out there from
various workshops that have been given by the NIH and FMRIB that you can
download and walk through.  Once you are familiar with those tools, I would
suggest setting up a repository to experiment with the nipype framework by
creating workflows.

On a final note, I am curious about what caught your eye about C-PAC.  What
made you interested in contributing, and how did you find out about us?

Best,
John Pellman

2015-10-13 5:16 GMT-04:00 Sourav Singh <notifications@github.com>:

**Comment by souravsingh** [comment]
@jpellman I had written a proposal during GSoC 2015 for INCF to implement network complexity for Connectomes.Although the proposal wasn't selected,I started experimenting in nipype and recently gave a talk at PyCon India 2015 on the same.

**Comment by anibalsolon** [comment]
Removed!
