### ISSUE TITLE
sRGB warning on cpac_gui launch using miniconda?

### ISSUE THREAD

**Issue by dclark87** [FCP-INDI/C-PAC#479]
Investigate the wx-miniconda related error where a window pops up on launching "cpac_gui" that warns about an sRGB error

**Comment by jpellman** [comment]
The source of this issue is that Miniconda uses a newer version of libpng (relative to the version installed on Ubuntu).  Ubuntu uses 1.2.x while Miniconda uses 1.6.17.  1.6.17 is more meticulous about errors in png files.  The solution to this is to install ImageMagick and run the 'find' command used in the following Spyder pull request: https://github.com/spyder-ide/spyder/pull/2216

I'll add this fix to the GUI branch.
