### ISSUE TITLE
Exception during benchmark QC

### ISSUE THREAD

**Issue by AndrewDDavis** [FCP-INDI/C-PAC#515]
I've installed C-PAC on a fresh Ubuntu 14.04 system and I'm attempting to get the benchmark pipeline to run.  I get the following warning, followed by an exception:

```
Warning: QC HTML pages could not be generated because the file names have become too long. Clear out the .html files present in the output directory and in the qc_files_here folders within the subject directories.
```

The full terminal output preceding the exception is posted [here](http://pastebin.com/kHCmVhzM).  I have tried the following strategies without success:
- clearing out .html files and re-running the pipeline
- shortening the name of the benchmark package directory to just `bm`

Any advice on getting the benchmark package to complete successfully would be greatly appreciated.

**Comment by jpellman** [comment]
Hi @AndrewDDavis ,

Are there any crash files in the crash directory?  If so, could you send them to my e-mail address at john.pellman@childmind.org ?

**Comment by AndrewDDavis** [comment]
My crash directory is empty.

**Comment by jpellman** [comment]
Hello @AndrewDDavis ,

Are you doing the run with fresh working and output directories?  If not, could you delete the old directories, create new ones, and then restart the run?  C-PAC may have issues when working and output directories from previous runs are still present, as these older directories can interfere with new runs (see [#3](http://fcp-indi.github.io/docs/user/help.html#common-issues-and-solutions) here).

**Comment by AndrewDDavis** [comment]
Thanks for your help with this problem.  I received the error after starting from a completely fresh state.  Basically what I've done on this machine is:

  - Installed Ubuntu
  - Installed CPAC
  - Downloaded and attempted to run the benchmark package, but received the above exception
  - Attempted to troubleshoot the exception

**Comment by ccraddock** [comment]
what is the path to the output directory? my guess is that it is getting
too long. I believe that C-PAC limits the output filepath size to 255
characters due to limitations with some of the tools that we rely on (AFNI
in most cases).

-cc

On Wed, Dec 9, 2015 at 3:00 PM, AndrewDDavis <notifications@github.com>
wrote:

> Thanks for your help with this problem. I received the error after
> starting from a completely fresh state. Basically what I've done on this
> machine is:
>
>    - Installed Ubuntu
>    - Installed CPAC
>    - Downloaded and attempted to run the benchmark package, but received
>    the above exception
>    - Attempted to troubleshoot the exception
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FCP-INDI/C-PAC/issues/515#issuecomment-163373599>.
>



-- 
Director of Imaging, Center for the Developing Brain, Child Mind Institute
<http://childmind.org>
Director, Computational NeuroImaging Lab
<http://computational-neuroimaging-lab.org/>, Nathan S. Kline Institute for
Psychiatric Research <http://www.rfmh.org/nki/>
Co-Founder, The Neuro Bureau <http://neurobureau.org>
Impact Story <https://impactstory.org/CameronCraddock>
Google Scholar Citations
<http://scholar.google.com/citations?user=lZ9hwSsAAAAJ&hl=en>
GitHub <https://github.com/ccraddock>
Share that Brain @ the International Neuroimaging Datasharing Initiative
<http://fcon_1000.projects.nitrc.org/>!
Join me 2015-10-23 @ Brainhack Americas <http://brainhack.org/Americas/>!
The GigaScience Brainhack Thematic Series
<http://brainhack.org/brainhack-thematic-series-call-for-papers/> is open
for your submission.

**Comment by AndrewDDavis** [comment]
I had the same thought, so I tried shortening it as much as I could.  I put the `benchmark_package` directory in my home directory and shortened it to `bm`.  So the path to the output directory is `/home/andrew/bm/output`.

**Comment by ccraddock** [comment]
frustrating ...

So here is the line of code that is generating the error:
https://github.com/FCP-INDI/C-PAC/blob/7965125125319d895464f40db57b0eaba9c84da3/CPAC/qc/utils.py#L1092

As you can see, the exception is not very specific and more than just a
filepath being too long can create this problem. Would you please verify
that you have write privileges to the output directory and that the disk is
not full?

Otherwise, Steve is working on refactoring the code to make the error
statement more informative and should be able to provide you with a patch
soon.

-cc


On Wed, Dec 9, 2015 at 3:29 PM, AndrewDDavis <notifications@github.com>
wrote:

> I had the same thought, so I tried shortening it as much as I could. I put
> the benchmark_package directory in my home directory and shortened it to
> bm. So the path to the output directory is /home/andrew/bm/output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FCP-INDI/C-PAC/issues/515#issuecomment-163383082>.
>



-- 
Director of Imaging, Center for the Developing Brain, Child Mind Institute
<http://childmind.org>
Director, Computational NeuroImaging Lab
<http://computational-neuroimaging-lab.org/>, Nathan S. Kline Institute for
Psychiatric Research <http://www.rfmh.org/nki/>
Co-Founder, The Neuro Bureau <http://neurobureau.org>
Impact Story <https://impactstory.org/CameronCraddock>
Google Scholar Citations
<http://scholar.google.com/citations?user=lZ9hwSsAAAAJ&hl=en>
GitHub <https://github.com/ccraddock>
Share that Brain @ the International Neuroimaging Datasharing Initiative
<http://fcon_1000.projects.nitrc.org/>!
Join me 2015-10-23 @ Brainhack Americas <http://brainhack.org/Americas/>!
The GigaScience Brainhack Thematic Series
<http://brainhack.org/brainhack-thematic-series-call-for-papers/> is open
for your submission.

**Comment by AndrewDDavis** [comment]
Thanks for continuing to look at this problem.  I do have the ability to write to `output/`, and `df` indicates I've got 162 Gb free.

I had the same thought about the except clause in utils.py being a bit liberal, so I did a quick edit on my local copy -- I just truncated the warning message and changed the raise command to be `raise` instead of `raise Exception`.  As I understand it, that should re-raise the original exception and tell us what it actually was.  It's been running for a while now, so I should have the output soon.

**Comment by AndrewDDavis** [comment]
And it just finished.  Here is the exception:

    Warning: ...


    Process Process-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_pipeline.py", line 5953, in prep_workflow
        generateQCPages(f_path, qc_montage_id_a, qc_montage_id_s, qc_plot_id, qc_hist_id)
      File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 1214, in generateQCPages
        make_qc_pages(qc_path, qc_montage_id_a, qc_montage_id_s, qc_plot_id, qc_hist_id)
      File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 1141, in make_qc_pages
        make_page(os.path.join(qc_path, file_), qc_montage_id_a, qc_montage_id_s, qc_plot_id, qc_hist_id)
      File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 1082, in make_page
        f_html_1)
      File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 864, in feed_lines_html
        png_h = dict_hist[id_][idx]
    IndexError: list index out of range

**Comment by ccraddock** [comment]
see, something else different altogether ;)

we will look into this and try to get back to you soon.

On Wed, Dec 9, 2015 at 4:45 PM, AndrewDDavis <notifications@github.com>
wrote:

> And it just finished. Here is the exception:
>
> Warning: ...
>
>
> Process Process-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_pipeline.py", line 5953, in prep_workflow
>     generateQCPages(f_path, qc_montage_id_a, qc_montage_id_s, qc_plot_id, qc_hist_id)
>   File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 1214, in generateQCPages
>     make_qc_pages(qc_path, qc_montage_id_a, qc_montage_id_s, qc_plot_id, qc_hist_id)
>   File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 1141, in make_qc_pages
>     make_page(os.path.join(qc_path, file_), qc_montage_id_a, qc_montage_id_s, qc_plot_id, qc_hist_id)
>   File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 1082, in make_page
>     f_html_1)
>   File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 864, in feed_lines_html
>     png_h = dict_hist[id_][idx]
> IndexError: list index out of range
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FCP-INDI/C-PAC/issues/515#issuecomment-163403825>.
>



-- 
Director of Imaging, Center for the Developing Brain, Child Mind Institute
<http://childmind.org>
Director, Computational NeuroImaging Lab
<http://computational-neuroimaging-lab.org/>, Nathan S. Kline Institute for
Psychiatric Research <http://www.rfmh.org/nki/>
Co-Founder, The Neuro Bureau <http://neurobureau.org>
Impact Story <https://impactstory.org/CameronCraddock>
Google Scholar Citations
<http://scholar.google.com/citations?user=lZ9hwSsAAAAJ&hl=en>
GitHub <https://github.com/ccraddock>
Share that Brain @ the International Neuroimaging Datasharing Initiative
<http://fcon_1000.projects.nitrc.org/>!
Join me 2015-10-23 @ Brainhack Americas <http://brainhack.org/Americas/>!
The GigaScience Brainhack Thematic Series
<http://brainhack.org/brainhack-thematic-series-call-for-papers/> is open
for your submission.

**Comment by AndrewDDavis** [comment]
I've done some more editing to try to shed some light on this issue.  I changed `utils.py` around line 863 to add a few print statements before the exception:

            if id_ in dict_hist:
                print 'id_ :', id_
                print 'dict_hist[id_] :', dict_hist[id_]
                print 'idx :', idx
                png_h = dict_hist[id_][idx]

The full output is [here](http://pastebin.com/9XKExQsv), but the last part before the exception is:

    id_ : 27
    dict_hist[id_] : ['/home/andrew/bm3/output/pipeline_ANTS_example/2014113_session_1/qc/sca_tempreg_maps_files_hist/_scan_rest_1_rest/_csf_threshold_0.98/_gm_threshold_0.7/_wm_threshold_0.98/_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic0.gm0.compcor1.csf1/_bandpass_freqs_0.009.0.1/_mask_HarvardOxford-cort-maxprob-thr50-2mm/sca_tempreg_maps_files_hist_plot.png', '/home/andrew/bm3/output/pipeline_ANTS_example/2014113_session_1/qc/sca_tempreg_maps_files_hist/_scan_rest_1_rest/_csf_threshold_0.98/_gm_threshold_0.7/_wm_threshold_0.98/_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic0.gm0.compcor1.csf1/_bandpass_freqs_0.009.0.1/_mask_HarvardOxford-sub-maxprob-thr50-2mm/sca_tempreg_maps_files_hist_plot.png', '/home/andrew/bm3/output/pipeline_ANTS_example/2014113_session_1/qc/sca_tempreg_maps_files_hist/_scan_rest_1_rest/_csf_threshold_0.98/_gm_threshold_0.7/_wm_threshold_0.98/_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic0.gm0.compcor1.csf1/_bandpass_freqs_0.009.0.1/_mask_rois_2mm/sca_tempreg_maps_files_hist_plot.png']
    idx : 3

So `dict_hist[id_]` does only have 3 entries, and `idx = 3` is therefore out of range, but beyond that I'm not sure if this output is helpful.  Let me know if I can try anything more to help get this cleared up.

**Comment by adliska** [comment]
I was wondering whether there are any updates regarding this issue or the refactoring mentioned by Cameron above? Otherwise I could also look into this myself some time in the near future.

**Comment by jpellman** [comment]
Hi @adliska ,

We're currently planning on removing the QC interface from the next release in order to focus on other areas of C-PAC.  We're planning on revisiting this functionality in future releases and will let you know if we need any help.

**Comment by sgiavasis** [comment]
If anyone on this thread revisits: the QC interface has been reintroduced in v1.1.0, and at least some of these issues have been resolved - would recommend trying again and seeing if you get the same problem.

Thank you!
