### ISSUE TITLE
"Some connections were not found" errors in CPAC_GUI

### ISSUE THREAD

**Issue by dtosun** [FCP-INDI/C-PAC#517]
I keep getting the following errors:

Some connections were not found
Module calc_ants_warp has no input called dimension

 Error allocating func_preproc. (/home/vhasfctosund/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py:1304)
Some connections were not found
Module func_motion_correct_A has no output called oned_matrix_save

Any suggestions?
Thanks

**Comment by jpellman** [comment]
Hi @dtosun ,

Could you send a copy of your pipeline configuration file to john.pellman@childmind.org ?  I'd like to take a look at it to better understand what might be going on here.

**Comment by jpellman** [comment]
Hello again @dtosun ,

Your configuration file looks okay (although I would suggest using a version of C-PAC greater than or equal to 0.3.9 if you aren't already, since that release makes some major fixes to scrubbing).  Could you try typing '3dvolreg' at a Unix terminal to verify that AFNI isn't exhibiting any problems that might be affecting C-PAC?  Also, could you send me any crash files that might be generated in your crash folder?

Best,
John Pellman

**Comment by sgiavasis** [comment]
Closing this issue because it has been awhile. If there are any more issues or questions, please feel free to open a new one.

Best,
The C-PAC Team
