### ISSUE TITLE
Trouble installation .matplolib

### ISSUE THREAD

**Issue by rfcasseb** [FCP-INDI/C-PAC#520]
Dear experts,

I tried to install C-PAC and I got the following error message:
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
chmod: cannot access ‘/home/rfc/.matplotlib’: No such file or directory
(it is the second time I am trying to install it today)

Do you have any idea of what I should do?

Thanks in advance,
Raphael

**Comment by jpellman** [comment]
Hi Raphael,

It looks like you're using cpac_install.sh.  One of the final things this script does is make a directory used by matplotlib writeable.  It looks like what has happened is that matplotlib has changed the path used for this directory in recent versions, so that it is now located at _/home/rfc/.config/matlplotli_b rather than _/home/rfc/.matplotlib_.  You can re-run this step with the new path by typing the following command in a fresh terminal:

> chmod -R 777 /home/rfc/.config/matlplotlib 

Afterwards, you should be able to type _cpac_gui_ and have the C-PAC interface appear.  If you continue to have difficulties, let me know so that we can troubleshoot some more.
