### ISSUE TITLE
Documentation for running C-PAC on multi-core single machine

### ISSUE THREAD

**Issue by transpersonify** [FCP-INDI/C-PAC#547]
I am running C-PAC on single machine with 8 cores. I have set up SGE on the system. However, I could not find documentation about how to configure SGE  so that C-PAC can make use of all 8 cores of the machine. 

Is it as simple as creating a new parallel environment named 'cpac'? If so, What is the configuration for parallelEnvironment :  cpac ?

Thanks.

**Comment by jpellman** [comment]
Hi @transpersonify.  For a single machine, you shouldn't need to use SGE (if you don't want to).  You can adjust the number of cores that your machine uses by changing the 'Number of Cores Per Subject' and 'Number of Cores for Anatomical Registration (ANTS only)' settings under _Environment Setup_ --> _Computer Settings_ in order to ensure that all 8 cores are used.

In terms of getting SGE up and running, the documentation could certainly include a bit more detail (thanks for bringing this to our attention).  Currently, our documentation provides instructions for setting up SGE within the context of our cloud-based AMI.  Essentially, our cloud-based AMI uses a Starcluster plugin to download [this parallel environment configuration](https://raw.githubusercontent.com/FCP-INDI/CPAC_CLOUD/master/mpi_smp.conf), and then executes the following two commands:

```
qconf -Ap /path/to/mpi_smp.conf
qconf -mattr queue pe_list "mpi_smp" all.q
```

If you were to execute these commands on your computer, you would then set the 'SGE Parallel Environment' field to 'mpi_smp' in your pipeline configuration. You may want to customize your parallel environment according to your specific needs, in which case [this parallel environment tutorial](https://blogs.oracle.com/templedf/entry/configuring_a_new_parallel_environment) from Oracle might prove useful.

**Comment by transpersonify** [comment]
Thank you so much for the details. Closing the issue.
