### ISSUE TITLE
C-PAC output question

### ISSUE THREAD

**Issue by mlzxzhou** [FCP-INDI/C-PAC#549]
Hi,

I have a question about the final output of C-PAC. I add temporal filtering into the processing which create a folder named 'bandpass_freqs' in the output directory. Since spatial smoothing should be the last step, so the folder 'fwhm' should be the subfolder of 'bandpass_freqs'. However, they are under the same directory, and the ''bandpass_freqs'' folder was created later than the 'fwhm' folder. So I was not sure which file should be the final output after applying all the processing procedures. Should it be the file 'motion_correct_to_standard_smooth.nii.gz' in the 'fwhm' folder or some other files? Thanks

**Comment by jpellman** [comment]
Hi @mlzxzhou ,

The motion-corrected data itself is not bandpassed, although it is smoothed.  Bandpassing occurs for measures such as ReHo and ALFF.  The directory structure for these smoothed and bandpassed outputs is generally of the following form:

`./<derivative name>_smooth/_scan_rest_1_rest/_scan_rest_1_rest/_csf_threshold_<threshold value>/_gm_threshold_<threshold value>/_wm_threshold_<threshold value>/_compcor_ncomponents_<number>_selector_pc1<0 or 1>.linear<0 or 1>.wm<0 or 1>.global<0 or 1>.motion<0 or 1>.quadratic<0 or 1>.gm<0 or 1>.compcor<0 or 1>.csf<0 or 1>/_bandpass_freqs_<lower frequency>.<higher frequency>`

**Comment by mlzxzhou** [comment]
Hi, John,

So should the final output after temporal filtering and smoothing file have the name 'functional_mni.nii.gz' in the folder you mentioned?

**Comment by jpellman** [comment]
The NifTI file name is dependent upon what the derivative is.  The file within the directory for the smoothed and bandpassed ReHo, for instance is "ReHo_maths.nii.gz". There should only be one file within the directory, however.  The directory path encodes the various pipeline options that were enabled so that you can identify the files that you want.

I also wanted to note a correction to my previous response- the path should include '_fwhm_<kernel size>' for the smoothing as well.  I have revised the response to reflect this.

**Comment by ccraddock** [comment]
Reho does not involve or reguire temporal filtering. Only Alff/falff specifically involve band pass filtering. For everything else bandpass filtering is optional.
