### ISSUE TITLE
motion parameters

### ISSUE THREAD

**Issue by mlzxzhou** [FCP-INDI/C-PAC#556]
Hi,

I have a question about the output about motion parameters. I guess it should be  'movement_parameters.1D' cause it has the same volume number with the resting data. But I was not sure why it has 24 columns, since usually it should be 6 dimensional corresponding to transition and rotation. From the plot in qc, seems like the first 6 columns is what I want. But another question is other tools like SPM, the 6 parameters at starting point should be 0, but it is different here. So could you help explain it? Thanks.

Best,
Fan

**Comment by jpellman** [comment]
Hi @mlzxzhou 

It looks like you had the [24 motion parameter model](http://fcp-indi.github.io/docs/user/motion.html#volume-realignment) enabled in your pipeline configuration.  For this set of regressors, the first 6 columns represent roll, pitch, yaw, superior displacement,  left displacement, and posterior displacement respectively for the current volume/row.  The next 18 columns are as described in the link above.  

The first 6 regressors are generated by AFNI's [3dVolreg](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dvolreg.html).  The values in the columns represent the values needed to align that particular row/volumes with a base image.  In C-PAC, 3dVolreg is run twice, with the base images used being a mean intensity RPI image and a motion-corrected mean intensity image (see [here](http://fcp-indi.github.io/docs/developer/workflows/func_preproc.html) for more details) instead of a single volume as a reference slice.  I believe that in SPM the default volume to use as a base image (reference scan) is the first volume, which is why your SPM outputs would normally be filled with 0s in the first row (since there would be no distance).

For further discussion of the differences between SPM and AFNI's motion regressor outputs (e.g., differences in measurement and column order) you might also want to see the following AFNI forum post [here](https://afni.nimh.nih.gov/afni/community/board/read.php?1,71385,71385#msg-71385).

Let me know if that clears things up,
John

**Comment by mlzxzhou** [comment]
Thanks, @jpellman . So my another question is that if any quality assessment results about motion correction is given in the output of C-PAC we could look at? Thanks.

**Comment by jpellman** [comment]
Hi @mlzxzhou 

The C-PAC QC interface outputs several images related to motion correction, including _FD_plot.png_, _motion_rot_plot.png_, and _motion_trans_plot.png_, which can be within the output directory of the form:

\<output\>/sym_links/pipeline_\<pipeline name\>/\<strategy name\>/\<participant\>/scan_rest_1_rest/qc

You can also view the values of various movement measures calculated by C-PAC using [extract_parameters.py](http://fcp-indi.github.io/docs/user/motion.html#regression-of-motion-parameters).  If you choose to do this, make sure to download the latest version from [here](https://raw.githubusercontent.com/FCP-INDI/C-PAC/0.4.0_development/CPAC/utils/extract_parameters.py), since the version of this script included with 0.3.9.2 has a known bug.

For more QA measures, you might also be interested in the [Quality Assessment Protocol package](http://preprocessed-connectomes-project.org/quality-assessment-protocol/) that our lab produces as well.

**Comment by jpellman** [comment]
It's also important to note that the QC interface will be disabled in the next release of C-PAC (0.4.0), so the  directory structure described above will only apply to versions 0.3.9.2 and older.
