### ISSUE TITLE
Preprocessed data

### ISSUE THREAD

**Issue by mlzxzhou** [FCP-INDI/C-PAC#575]
Hi,

I just want to know if is possible to skip the processing step of C-PAC and move to the step of extracting time series of ROIs directly when the data is already preprocessed. If possible, how to set the pipeline? Thanks.

**Comment by jpellman** [comment]
Hi @mlzxzhou ,

Unfortunately it is not currently possible to take data that has already been preprocessed with a different pipeline and calculate outputs  This functionality is very commonly requested and we hope to offer it in future releases.

Also, are you a member of our forum [here](https://groups.google.com/forum/#!forum/cpax_forum)?  It might be better to post this kind of question on the forum instead of here in the future, since we also use this issue tracker for our software development process (e.g., keeping track of bugs, feature requests).
