### ISSUE TITLE
ImportError: No module named CPAC (Ubuntu 16.0.4)

### ISSUE THREAD

**Issue by Larry-Lai** [FCP-INDI/C-PAC#756]
Dear C-PAC experts

Thanks for considering my request.

--
~$ ipython
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19) 
Type "copyright", "credits" or "license" for more information.

IPython 5.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import CPAC
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-45be67b94719> in <module>()
----> 1 import CPAC

ImportError: No module named CPAC
--

Best wishes
Larry

**Comment by sgiavasis** [comment]
Hi @Larry-Lai,

How did you install CPAC on your system? i.e. through a Git repo, or by downloading the tarball, etc.?

Best,
Steve

**Comment by Larry-Lai** [comment]
Hi Steve

wget https://github.com/FCP-INDI/C-PAC/blob/master/scripts/cpac_install.sh?raw=true
mv cpac_install.sh?raw=true cpac_install.sh
chmod +x cpac_install.sh
sudo ./cpac_install.sh -r

Best regards
Larry

**Comment by sgiavasis** [comment]
Hi @Larry-Lai,

It seems like the install script didn't complete properly- did it provide any sort of message? I'd like to find out where it went wrong (if it did) and fix it so that it won't happen next time.

In the meantime, if you need to get running ASAP, you can try filling the gaps manually:

**Python dependencies:**
`pip install networkx==1.11 jinja2==2.7.2 nipype==0.13.1 scipy numpy nibabel traits matplotlib pyyaml patsy boto3 psutil INDI-Tools prov simplejson pandas cython lockfile`

**AFNI & FSL:**
http://fcp-indi.github.io/docs/user/install.html#installing-afni-and-fsl

**Image Resources:**
http://fcp-indi.github.io/docs/user/install.html#installing-c-pac-image-resources

**CPAC Itself:**
http://fcp-indi.github.io/docs/user/install.html#id11

Please let me know if you have any issues- anything that serves as a hurdle or inconvenience is something we'd like to improve or remove.

Thanks!
Steve

**Comment by Larry-Lai** [comment]
Hi Steve

Thanks so much for your quick reply and solution.

I`ll try it again to reproduce the results. 

Best wishes
Larry

**Comment by sgiavasis** [comment]
Hi @Larry-Lai,

Mostly the same, with a few small differences/potential options:
[http://fcp-indi.github.io/docs/user/install.html#id2](http://fcp-indi.github.io/docs/user/install.html#id2)
[http://fcp-indi.github.io/docs/user/install.html#id6(http://fcp-indi.github.io/docs/user/install.html#id6)

Steve

**Comment by Larry-Lai** [comment]
Hi Steve

I managed to get CPAC-GUI up by filling the following gaps manually"
**1. pip install INDI-Tools
2. Re-install CPAC itself**
3. From the terminal:
~$ ipython
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19) 
Type "copyright", "credits" or "license" for more information.

IPython 5.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: **import CPAC.GUI**

In [2]: **CPAC.GUI.run()**

Thanks so much for your help.

Best wishes
Larry Lai

**Comment by sgiavasis** [comment]
Hi @Larry-Lai,

Thanks for reporting back with what worked. I'm going to go through the install script and patch where necessary.

Best,
Steve
