### ISSUE TITLE
slice timing pattern

### ISSUE THREAD

**Issue by tliu47** [FCP-INDI/C-PAC#823]
Hi! I have been using the 1.2.0 version CPAC. After submitting my own pipeline file, I saw this error

Error connecting input 'acquisition' to func_slice_timing_correction afni node. (/usr/local/miniconda/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py:1530)
'Configuration' object has no attribute 'slice_timing_patter'

I checked the code on https://github.com/FCP-INDI/C-PAC/blob/34066fc2da76b279506c5dd7c335dac19651cb49/CPAC/pipeline/cpac_pipeline.py and was confused by line 1525. I am a beginner but could it be a typo?

I really love your pipeline by the way and thank you so much!

**Comment by nrajamani3** [comment]
Hi tliu47,

You are correct in that it is a typo. We are going to fix that, and a few
other quick fixes in our next point release.
Since this is an emergency situation for you - I would suggest to change
your local scripts.
You can do this by navigating to ~/C-PAC/CPAC/pipeline/cpac_pipeline.py and
going to line 1525 where you can fix "patter" to "pattern". Following this,
you would have to re-install CPAC by using your terminal and typing:
$ python setup.py install

Thank you for reaching out,
Nanditha

**Comment by anibalsolon** [comment]
Hi @tliu47 

This error has been fixed in newer versions of C-PAC.

Please, open a new issue if you find new problems or have questions!
