### ISSUE TITLE
C-PAC cannot find the scan parameters file when it exists

### ISSUE THREAD

**Issue by cmoroz1** [FCP-INDI/C-PAC#851]
I am running C-PAC from Docker, but I keep getting an error that C-PAC cannot find the scan parameter JSON file listed in my data config file. The command I am using to run Docker is:

docker run -i --rm \
	-v /home/neurolab/Desktop/bidsdir/BIDS_Format:/bids_dataset \
	-v /home/neurolab/Desktop/bidsdir/runs/pipeline01/output:/outputs \
	-v /home/neurolab/Desktop/bidsdir/runs/pipeline01/work:/scratch \
	-v /home/neurolab/Desktop/bidsdir/configs:/configs \
	-v /home/neurolab/Desktop/bidsdir/resources:/resources \
	childmind/c-pac:latest /bids_dataset /outputs participant --data_config_file /configs/data_config_testing.yml

I have also attached my data and pipeline config and setting files as well as the two crash files that Nipype generated in a ZIP file. Please let me know if you need anything else. I am not sure how to fix this error. Thank you in advance for your time and help.

[files.zip](https://github.com/FCP-INDI/C-PAC/files/2543779/files.zip)

**Comment by anibalsolon** [comment]
Hi @cmoroz1 

Thank you for reaching out!

The problem here is that you are trying to use paths from your desktop on docker. For example, in the data_config_testing.yml:

```
/home/neurolab/Desktop/bidsdir/BIDS_Format/Subjects/sub-A00075674/anat/sub-A00075674_T1w.nii.gz
```

but it should be

```
/bids_dataset/Subjects/sub-A00075674/anat/sub-A00075674_T1w.nii.gz
```

because you are linking the folder `/home/neurolab/Desktop/bidsdir/BIDS_Format` to `/bids_dataset` on the `docker run` command.

So basically replace all `/home/neurolab/Desktop/bidsdir/BIDS_Format` in your data config file to `/bids_dataset`. Also change your folder in the pipeline config to its respective link on docker.

Please let us know if it works and/or if you need further support!

**Comment by cmoroz1** [comment]
Thank you, that fixed the error.
