### ISSUE TITLE
advanced parameters for 3dskullstrip, BET, etc

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#937]
how the advanced parameters are listed in the pipeline config file can lead to confusion, would it be possible to put them in a nested dictionary so that they are more seperated from other params?

**Comment by anibalsolon** [comment]
Yes, we can make it into a dictionary, and even strip some options that are
just options to generate some outputs, instead of parametrizing the skull
stripping process. E.g. on BET:

skull: (a boolean)
        create skull image
        argument: ``-s``

since it is not part of CPAC outputs, there is no reason to have this
option on the pipeline config.

**Comment by sgiavasis** [comment]
#1278 on the slate!

**Comment by sgiavasis** [comment]
This is in v1.8.
